# Global options
baseurl = "https://calm-workshop-2024.github.io/"
canonifyurls = true
languagecode = "en"
theme = "crl-uai-2022-theme"
disableKinds = ["taxonomyTerm"]

# Params that are used in <head>
[params]
  supertitle = "C♥️LM: First Workshop on"
  title = "Causality and Large Models"
  subtitle = "December @ NeurIPS 2024"
  author = "Felix Leeb, Ching Lam Choi, Luigi Gresele, Josef Valvoda, Andrei Nicolicioiu, Xiusi Li, Patrik Reizinger, Sophie Xhonneux, Haoxuan Li, Mengyue Yang, Bernhard Schölkopf, Dhanya Sridhar"
  description = "First Workshop on Causality and Large Models (C♥️LM) @ NeurIPS 2024"
  keywords = ["workshop", "causal representation learning", "large models", "foundation models"]

# Options for Markdown renderer
[markup.goldmark.renderer]
  unsafe = true
  xHTML = true

# Main menu

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1

[[menu.main]]
    name = "Call for Papers"
    url  = "/call-for-papers"
    weight = 2

[[menu.main]]
    name = "Dates"
    url  = "/dates"
    weight = 3
[[menu.main]]
    name = "Schedule"
    url  = "/schedule"
    weight = 4
[[menu.main]]
    name = "Our Team"
    url  = "/team"
    weight = 5
[[menu.main]]
    name = "Invited Speakers"
    url  = "/invited-speakers"
    weight = 6
[[menu.main]]
    name = "Accepted Papers"
    url  = "/accepted-papers"
    weight = 7